# Stage 09 — Homework Starter Notebook

In the lecture, we learned how to create engineered features. Now it’s your turn to apply those ideas to your own project data.

In [4]:
import pandas as pd
import numpy as np

# Example synthetic data (replace with your project dataset)
df = pd.read_csv('prices_util_20250821-180125.csv')
df.head()

         date    aapl  VCNIX
0  2025-03-28  217.90  20.83
1  2025-03-31  222.13  20.83
2  2025-04-01  223.19  21.00
3  2025-04-02  223.89  21.16
4  2025-04-03  203.19  20.01

## TODO: Implement at least 2 engineered features here

In [8]:
# Example template:
df['aapl_VCNIX_ratio'] = df['aapl'] / df['VCNIX']  # TODO: Your feature
# Add rationale in markdown below

### Rationale for Feature 1
To see how is the AAPL stock price change against the VCNIX index.

In [9]:
# TODO: Add another feature
df['rolling_aapl_mean'] = df['aapl'].rolling(3).mean()
df

          date    aapl  VCNIX  rolling_aapl_mean  aapl_VCNIX_ratio
0   2025-03-28  217.90  20.83                NaN         10.460874
1   2025-03-31  222.13  20.83                NaN         10.663946
2   2025-04-01  223.19  21.00         221.073333         10.628095
3   2025-04-02  223.89  21.16         223.070000         10.580813
4   2025-04-03  203.19  20.01         216.756667         10.154423
..         ...     ...    ...                ...               ...
95  2025-08-14  232.78  25.76         231.920000          9.036491
96  2025-08-15  231.59  25.63         232.566667          9.035895
97  2025-08-18  230.89  25.63         231.753333          9.008584
98  2025-08-19  230.56  25.28         231.013333          9.120253
99  2025-08-20  226.01  25.13         229.153333          8.993633

[100 rows x 5 columns]

### Rationale for Feature 2
Checking the 3 day mean of the AAPl stock price to find a trend.